
const PORT = process.env.PORTDEV || 8081
const STRC = process.env.STRC
const NAMEBASE = process.env.NAMEBASE
const PERSISTENCEGAMES = process.env.PERSISTENCEGAMES
const PERSISTENCECONSOLES = process.env.PERSISTENCECONSOLES
const LOCALPERSISTENCEGAMES = process.env.LOCALPERSISTENCEGAMES
const LOCALPERSISTENCECONSOLES = process.env.LOCALPERSISTENCECONSOLES

export default {
    PORT,
    STRC,
    NAMEBASE,
    PERSISTENCEGAMES,
    PERSISTENCECONSOLES,
    LOCALPERSISTENCECONSOLES,
    LOCALPERSISTENCEGAMES
}

